apiVersion: v1
kind: ServiceAccount
metadata:
  name: py-node-health
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodes-list
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodes-list
subjects:
- kind: ServiceAccount
  name: py-node-health
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nodes-list
  apiGroup: rbac.authorization.k8s.io
